### ISSUE TITLE
conflit de cat entre la glose et la catégorisation spécifiée dans la page d'un lemma

### ISSUE THREAD

**Issue by MJouitteau** [Autogramm/Breton#4]
dans les cas de conflit de catégorie grammaticale entre la glose et la catégorisation spécifiée dans la page d'un lemma, l'hésitation  devrait être résolue en suivant la glose. 
Ce sera toujours le cas lors d'un conflit de catégorisation: la glose a été faite à la main pour chaque cas particulier, alors que la page d'adresse d'un lemma regroupe toutes ses catégorisations recensées. 

```
# sent_id = Herri(1982:57)__1
# text = evit kas un daouzegad boutailhoù gwin.
# text_fr = 'pour envoyer une douzaine de bouteilles de vin'
# source = Herri (1982)
# texttype = Références de corpus
1	evit	evit	préposition|complémenteur	_	_	_	_	_	Gloss=pour
2	kas	kas	verbe	_	_	_	_	_	Gloss=envoyer
3	un	art	déterminant|quantifieur	_	_	_	_	_	Gloss=un
4	daouzegad	cardinaux	adjectif|quantifieur	_	_	_	_	_	Gloss=douze
5	boutailhoù	boutailh.-où_(PL.)	nom.suffixe	_	_	_	_	_	Gloss=bouteille.s
6	gwin	gwin	nom	_	_	_	_	_	Gloss=vin
7	.	.	PUNCT	_	_	_	_	_	Gloss=punct


idem:
# sent_id = L'Hôpital-Camfrout,LeGall(1958)__1
6	hag	&	conjonction|complémenteur

idem:
# sent_id = HorYezh(1983:17)__1
1	Barzh	e-barzh	préposition|postposition

**Comment by salomechandora** [comment]
Le problème n'est pas réglé car je ne suis pas sûre de comprendre en quoi il y a conflit. Les codes source des exemples ci-dessus sont : 

**Exemple 1:** 
{| class="prettytable"
|(1)|| evit || kas || un daouzegad || boutailhoù || '''gwin'''. 
|-
||| [[evit|pour]] || [[kas|envoyer]] || [[art|un]] [[cardinaux|douze]].[[-ad|ée]] || [[boutailh|bouteille]].[[-où (PL.)|s]] || vin
|-
|||colspan="15" | 'pour envoyer une douzaine de bouteilles de vin'
|-
|||||||colspan="15" | ''Standard'', [[Herri (1982)|Herri (1982]]:57)
|}

**Exemple 2:** 
 [[e-barzh|dans]] 

**Exemple 3:**
 [[&|et]]

Sauf erreur de ma part, la catégorie grammaticale n'est pas précisée dans la glose. A ce stade, le script fait simplement de la récupération de données, il n'y a aucune analyse linguistique. Par conséquent, on ne peut que récupérer les catégories de la page du lemme.

**Comment by MJouitteau** [comment]
Je comprends. On peut trouver des règles de désambiguïsation plus tard.
